const actions = {
  ADD_HORIZONTAL_CARD: "ADD_HORIZONTAL_CARD",
  ADD_VERTICAL_LIST: "ADD_VERTICAL_LIST",
  DRAG_SUCCESS: "DRAG_SUCCESS",
  DELETE_LIST: "DELETE_LIST",
  EDIT_CARD: "EDIT_CARD",
  DELETE_CARD: "DELETE_CARD"
}

export {actions};
